FALLBACK_DATA = [
    {
        "match_date": "2024-11-24",
        "team1": "India",
        "team2": "Australia",
        "venue": "Perth Stadium, Perth",
        "winner": "India",
        "top_scorer": "Yashasvi Jaiswal",
        "top_score": 161,
        "home_team": "Australia",
    },
    {
        "match_date": "2024-11-22",
        "team1": "India",
        "team2": "Australia",
        "venue": "Adelaide Oval, Adelaide",
        "winner": "Australia",
        "top_scorer": "Travis Head",
        "top_score": 140,
        "home_team": "Australia",
    },
    {
        "match_date": "2024-11-06",
        "team1": "India",
        "team2": "South Africa",
        "venue": "Centurion Park, Centurion",
        "winner": "South Africa",
        "top_scorer": "Temba Bavuma",
        "top_score": 106,
        "home_team": "South Africa",
    },
    {
        "match_date": "2024-10-20",
        "team1": "India",
        "team2": "New Zealand",
        "venue": "M. Chinnaswamy Stadium, Bengaluru",
        "winner": "New Zealand",
        "top_scorer": "Will Young",
        "top_score": 89,
        "home_team": "India",
    },
    {
        "match_date": "2024-09-29",
        "team1": "India",
        "team2": "Bangladesh",
        "venue": "MA Chidambaram Stadium, Chennai",
        "winner": "India",
        "top_scorer": "Virat Kohli",
        "top_score": 47,
        "home_team": "India",
    },
    {
        "match_date": "2024-07-29",
        "team1": "India",
        "team2": "Sri Lanka",
        "venue": "Pallekele International Cricket Stadium",
        "winner": "India",
        "top_scorer": "Shubman Gill",
        "top_score": 98,
        "home_team": "Sri Lanka",
    },
    {
        "match_date": "2024-06-29",
        "team1": "India",
        "team2": "South Africa",
        "venue": "Kensington Oval, Barbados",
        "winner": "India",
        "top_scorer": "Virat Kohli",
        "top_score": 76,
        "home_team": "Neutral",
    },
    {
        "match_date": "2024-06-22",
        "team1": "India",
        "team2": "England",
        "venue": "Providence Stadium, Guyana",
        "winner": "India",
        "top_scorer": "Rohit Sharma",
        "top_score": 57,
        "home_team": "Neutral",
    },
    {
        "match_date": "2024-06-15",
        "team1": "India",
        "team2": "Pakistan",
        "venue": "Nassau County International Cricket Stadium, New York",
        "winner": "India",
        "top_scorer": "Virat Kohli",
        "top_score": 76,
        "home_team": "Neutral",
    },
    {
        "match_date": "2024-02-04",
        "team1": "India",
        "team2": "Afghanistan",
        "venue": "ACA-VDCA Cricket Stadium, Visakhapatnam",
        "winner": "India",
        "top_scorer": "Shubman Gill",
        "top_score": 126,
        "home_team": "India",
    },
    # ── Australia last 10 results ────────────────────────────────────────────
    {
        "match_date": "2024-11-24",
        "team1": "Australia",
        "team2": "India",
        "venue": "Perth Stadium, Perth",
        "winner": "India",
        "top_scorer": "Yashasvi Jaiswal",
        "top_score": 161,
        "home_team": "Australia",
    },
    {
        "match_date": "2024-11-22",
        "team1": "Australia",
        "team2": "India",
        "venue": "Adelaide Oval, Adelaide",
        "winner": "Australia",
        "top_scorer": "Travis Head",
        "top_score": 140,
        "home_team": "Australia",
    },
    {
        "match_date": "2024-10-05",
        "team1": "Australia",
        "team2": "Pakistan",
        "venue": "Gaddafi Stadium, Lahore",
        "winner": "Pakistan",
        "top_scorer": "Babar Azam",
        "top_score": 111,
        "home_team": "Pakistan",
    },
    {
        "match_date": "2024-09-22",
        "team1": "Australia",
        "team2": "England",
        "venue": "Lord's Cricket Ground, London",
        "winner": "Australia",
        "top_scorer": "Travis Head",
        "top_score": 118,
        "home_team": "England",
    },
    {
        "match_date": "2024-09-11",
        "team1": "Australia",
        "team2": "England",
        "venue": "The Oval, London",
        "winner": "England",
        "top_scorer": "Joe Root",
        "top_score": 143,
        "home_team": "England",
    },
    {
        "match_date": "2024-07-14",
        "team1": "Australia",
        "team2": "West Indies",
        "venue": "Daren Sammy National Cricket Stadium, St Lucia",
        "winner": "Australia",
        "top_scorer": "David Warner",
        "top_score": 91,
        "home_team": "West Indies",
    },
    {
        "match_date": "2024-06-21",
        "team1": "Australia",
        "team2": "Afghanistan",
        "venue": "Arnos Vale Ground, St Vincent",
        "winner": "Afghanistan",
        "top_scorer": "Rahmanullah Gurbaz",
        "top_score": 60,
        "home_team": "Neutral",
    },
    {
        "match_date": "2024-02-29",
        "team1": "Australia",
        "team2": "New Zealand",
        "venue": "Basin Reserve, Wellington",
        "winner": "Australia",
        "top_scorer": "Mitchell Marsh",
        "top_score": 90,
        "home_team": "New Zealand",
    },
    {
        "match_date": "2024-02-21",
        "team1": "Australia",
        "team2": "New Zealand",
        "venue": "Hagley Oval, Christchurch",
        "winner": "New Zealand",
        "top_scorer": "Kane Williamson",
        "top_score": 85,
        "home_team": "New Zealand",
    },
    {
        "match_date": "2024-01-19",
        "team1": "Australia",
        "team2": "West Indies",
        "venue": "Adelaide Oval, Adelaide",
        "winner": "Australia",
        "top_scorer": "Steve Smith",
        "top_score": 94,
        "home_team": "Australia",
    },
]